export type Env = "chat" | "code" | "both";

export interface Skill {
  id: string;
  name: string;
  command: string;
  domain: string;
  env: Env;
  description: string;
  reportCount?: number;
  folderPath: string;
}

export const skills: Skill[] = [
  // web-hunting (22)
  {
    id: "web-hunting/hunt-sqli",
    name: "SQLi Hunter",
    command: "/hunt-sqli",
    domain: "web-hunting",
    env: "both",
    description: "SQL and NoSQL injection across ORM raw fragments, GraphQL resolvers, OIDC-proxy backends, and SOQL. Built from 12 disclosed reports including CVE-2021-22911 and CVE-2024-53900.",
    reportCount: 12,
    folderPath: "skills/web-hunting/hunt-sqli",
  },
  {
    id: "web-hunting/hunt-xss",
    name: "XSS Hunter",
    command: "/hunt-xss",
    domain: "web-hunting",
    env: "both",
    description: "Cross-site scripting across DOM, reflected, stored, and mutation-based patterns. Built from 174 public bug bounty reports.",
    reportCount: 174,
    folderPath: "skills/web-hunting/hunt-xss",
  },
  {
    id: "web-hunting/hunt-ssrf",
    name: "SSRF Hunter",
    command: "/hunt-ssrf",
    domain: "web-hunting",
    env: "both",
    description: "Server-side request forgery including cloud metadata endpoint exfiltration, internal network pivoting, and webhook abuse patterns.",
    folderPath: "skills/web-hunting/hunt-ssrf",
  },
  {
    id: "web-hunting/hunt-rce",
    name: "RCE Hunter",
    command: "/hunt-rce",
    domain: "web-hunting",
    env: "both",
    description: "Remote code execution via deserialization, template injection, command injection, and unsafe eval patterns derived from real disclosures.",
    folderPath: "skills/web-hunting/hunt-rce",
  },
  {
    id: "web-hunting/hunt-idor",
    name: "IDOR Hunter",
    command: "/hunt-idor",
    domain: "web-hunting",
    env: "both",
    description: "Insecure direct object references including BOLA in REST/GraphQL, ID enumeration, and horizontal privilege escalation. Built from 26 reports.",
    reportCount: 26,
    folderPath: "skills/web-hunting/hunt-idor",
  },
  {
    id: "web-hunting/hunt-csrf",
    name: "CSRF Hunter",
    command: "/hunt-csrf",
    domain: "web-hunting",
    env: "both",
    description: "Cross-site request forgery including SameSite bypass, token fixation, and JSON-based CSRF in single-page apps.",
    folderPath: "skills/web-hunting/hunt-csrf",
  },
  {
    id: "web-hunting/hunt-ssti",
    name: "SSTI Hunter",
    command: "/hunt-ssti",
    domain: "web-hunting",
    env: "both",
    description: "Server-side template injection across Jinja2, Twig, Freemarker, Velocity, and Pebble with RCE escalation paths.",
    folderPath: "skills/web-hunting/hunt-ssti",
  },
  {
    id: "web-hunting/hunt-xxe",
    name: "XXE Hunter",
    command: "/hunt-xxe",
    domain: "web-hunting",
    env: "both",
    description: "XML external entity injection including blind OOB exfiltration, file read via error messages, and XXE-to-SSRF chains.",
    folderPath: "skills/web-hunting/hunt-xxe",
  },
  {
    id: "web-hunting/hunt-file-upload",
    name: "File Upload Hunter",
    command: "/hunt-file-upload",
    domain: "web-hunting",
    env: "both",
    description: "Unrestricted file upload bypasses — MIME type spoofing, extension trickery, polyglots, path traversal via filename.",
    folderPath: "skills/web-hunting/hunt-file-upload",
  },
  {
    id: "web-hunting/hunt-cache-poison",
    name: "Cache Poison Hunter",
    command: "/hunt-cache-poison",
    domain: "web-hunting",
    env: "both",
    description: "Web cache poisoning via unkeyed headers, parameter cloaking, fat GET exploitation, and cache-key normalization bugs.",
    folderPath: "skills/web-hunting/hunt-cache-poison",
  },
  {
    id: "web-hunting/hunt-http-smuggling",
    name: "HTTP Smuggling Hunter",
    command: "/hunt-http-smuggling",
    domain: "web-hunting",
    env: "code",
    description: "HTTP request smuggling — CL.TE, TE.CL, TE.TE variants with bypass and response queue poisoning escalation.",
    folderPath: "skills/web-hunting/hunt-http-smuggling",
  },
  {
    id: "web-hunting/hunt-race-condition",
    name: "Race Condition Hunter",
    command: "/hunt-race-condition",
    domain: "web-hunting",
    env: "code",
    description: "Race condition exploitation on payment flows, coupon redemption, rate-limit bypass, and parallel request amplification.",
    folderPath: "skills/web-hunting/hunt-race-condition",
  },
  {
    id: "web-hunting/hunt-business-logic",
    name: "Business Logic Hunter",
    command: "/hunt-business-logic",
    domain: "web-hunting",
    env: "both",
    description: "Business logic flaws — price manipulation, workflow bypass, state machine abuse, and trust boundary violations.",
    folderPath: "skills/web-hunting/hunt-business-logic",
  },
  {
    id: "web-hunting/hunt-graphql",
    name: "GraphQL Hunter",
    command: "/hunt-graphql",
    domain: "web-hunting",
    env: "both",
    description: "GraphQL introspection abuse, batching attacks, IDOR through aliases, nested query DoS, and authorization bypass.",
    folderPath: "skills/web-hunting/hunt-graphql",
  },
  {
    id: "web-hunting/hunt-llm-ai",
    name: "LLM/AI Hunter",
    command: "/hunt-llm-ai",
    domain: "web-hunting",
    env: "both",
    description: "LLM-integrated application vulnerabilities — prompt injection, insecure tool use, training data extraction, and model denial of service.",
    folderPath: "skills/web-hunting/hunt-llm-ai",
  },
  {
    id: "web-hunting/hunt-dispatch",
    name: "Dispatch Hunter",
    command: "/hunt-dispatch",
    domain: "web-hunting",
    env: "code",
    description: "Smart target triage and hunting path dispatch — routes to the right skill based on reconnaissance signals.",
    folderPath: "skills/web-hunting/hunt-dispatch",
  },
  {
    id: "web-hunting/hunt-misc",
    name: "Misc Vuln Hunter",
    command: "/hunt-misc",
    domain: "web-hunting",
    env: "both",
    description: "Catch-all for open redirect, CRLF injection, clickjacking, host header injection, and other frequently disclosed low-to-medium classes.",
    folderPath: "skills/web-hunting/hunt-misc",
  },
  {
    id: "web-hunting/hunt-aspnet",
    name: "ASP.NET Hunter",
    command: "/hunt-aspnet",
    domain: "web-hunting",
    env: "both",
    description: "ASP.NET-specific attack surface — ViewState deserialization, __EVENTTARGET manipulation, IIS short filename disclosure, and Razor injection.",
    folderPath: "skills/web-hunting/hunt-aspnet",
  },
  {
    id: "web-hunting/bug-bounty",
    name: "Bug Bounty Planner",
    command: "/bug-bounty",
    domain: "web-hunting",
    env: "both",
    description: "Structured methodology for scoping, prioritizing, and executing a bug bounty engagement from program selection to final submission.",
    folderPath: "skills/web-hunting/bug-bounty",
  },
  {
    id: "web-hunting/bb-methodology",
    name: "BB Methodology",
    command: "/bb-methodology",
    domain: "web-hunting",
    env: "both",
    description: "End-to-end bug bounty methodology — recon, attack surface mapping, vulnerability testing order, and triage workflow.",
    folderPath: "skills/web-hunting/bb-methodology",
  },
  {
    id: "web-hunting/bb-local-toolkit",
    name: "Local Toolkit",
    command: "/bb-local-toolkit",
    domain: "web-hunting",
    env: "code",
    description: "Local toolchain setup for bug bounty — ffuf, nuclei, sqlmap, burp configurations, and wordlist management.",
    folderPath: "skills/web-hunting/bb-local-toolkit",
  },
  {
    id: "web-hunting/security-arsenal",
    name: "Security Arsenal",
    command: "/security-arsenal",
    domain: "web-hunting",
    env: "both",
    description: "Curated command arsenal for web security testing — one-liner reference for recon, fuzzing, exploitation, and post-exploitation.",
    folderPath: "skills/web-hunting/security-arsenal",
  },

  // auth-identity (5)
  {
    id: "auth/hunt-oauth",
    name: "OAuth Hunter",
    command: "/hunt-oauth",
    domain: "auth",
    env: "both",
    description: "OAuth 2.0 and OIDC vulnerabilities — CSRF on redirect_uri, state fixation, code injection, token leakage, and open redirect chains. Built from 19 reports.",
    reportCount: 19,
    folderPath: "skills/auth-identity/hunt-oauth",
  },
  {
    id: "auth/hunt-ato",
    name: "ATO Hunter",
    command: "/hunt-ato",
    domain: "auth",
    env: "both",
    description: "Account takeover chains — password reset poisoning, username enumeration, token predictability, and session fixation patterns.",
    folderPath: "skills/auth-identity/hunt-ato",
  },
  {
    id: "auth/hunt-auth-bypass",
    name: "Auth Bypass Hunter",
    command: "/hunt-auth-bypass",
    domain: "auth",
    env: "both",
    description: "Authentication bypass — JWT alg=none, weak HMAC secrets, path traversal in auth middleware, and HTTP verb override bypass.",
    folderPath: "skills/auth-identity/hunt-auth-bypass",
  },
  {
    id: "auth/hunt-mfa-bypass",
    name: "MFA Bypass Hunter",
    command: "/hunt-mfa-bypass",
    domain: "auth",
    env: "both",
    description: "Multi-factor authentication bypass — code reuse, race conditions on OTP validation, backup code enumeration, and SIM-swap-adjacent flows.",
    folderPath: "skills/auth-identity/hunt-mfa-bypass",
  },
  {
    id: "auth/hunt-saml",
    name: "SAML Hunter",
    command: "/hunt-saml",
    domain: "auth",
    env: "both",
    description: "SAML SSO vulnerabilities — signature wrapping, XML comment injection, NameID manipulation, and SP-initiated flow abuse.",
    folderPath: "skills/auth-identity/hunt-saml",
  },

  // api-infra (4)
  {
    id: "api-infra/hunt-api-misconfig",
    name: "API Misconfig Hunter",
    command: "/hunt-api-misconfig",
    domain: "api-infra",
    env: "both",
    description: "API security misconfiguration — mass assignment, JWT attacks, prototype pollution, CORS wildcard with credentials, and HTTP verb tampering.",
    folderPath: "skills/api-infra/hunt-api-misconfig",
  },
  {
    id: "api-infra/hunt-cloud-misconfig",
    name: "Cloud Misconfig Hunter",
    command: "/hunt-cloud-misconfig",
    domain: "api-infra",
    env: "both",
    description: "Cloud storage and service misconfiguration — S3 bucket ACL, GCS bucket enumeration, Azure blob public access, and metadata endpoint exposure.",
    folderPath: "skills/api-infra/hunt-cloud-misconfig",
  },
  {
    id: "api-infra/hunt-graphql",
    name: "GraphQL Deep Dive",
    command: "/hunt-graphql",
    domain: "api-infra",
    env: "both",
    description: "GraphQL security deep dive — introspection bypass, batching amplification, field-level authorization bypass, and subscription abuse.",
    folderPath: "skills/api-infra/hunt-graphql",
  },
  {
    id: "api-infra/hunt-ntlm-info",
    name: "NTLM Info Hunter",
    command: "/hunt-ntlm-info",
    domain: "api-infra",
    env: "code",
    description: "NTLM information disclosure — internal hostname/domain leak via 401 challenges on web-exposed endpoints, NTLM relay preconditions.",
    folderPath: "skills/api-infra/hunt-ntlm-info",
  },

  // enterprise (6)
  {
    id: "enterprise/cloud-iam-deep",
    name: "Cloud IAM Deep",
    command: "/cloud-iam-deep",
    domain: "enterprise",
    env: "both",
    description: "Cloud IAM attack chains across AWS, Azure, GCP — STS/AssumeRole chaining, Managed Identity abuse via SSRF, 24+ AWS privesc patterns.",
    reportCount: 6,
    folderPath: "skills/enterprise/cloud-iam-deep",
  },
  {
    id: "enterprise/m365-entra-attack",
    name: "M365/Entra Attack",
    command: "/m365-entra-attack",
    domain: "enterprise",
    env: "both",
    description: "Microsoft 365 and Entra ID attack surface — OAuth app consent phishing, token exfiltration via device flow, PRT abuse, and conditional access bypass.",
    folderPath: "skills/enterprise/m365-entra-attack",
  },
  {
    id: "enterprise/okta-attack",
    name: "Okta Attack",
    command: "/okta-attack",
    domain: "enterprise",
    env: "both",
    description: "Okta attack patterns — password spray against admin portal, impersonation API abuse, factor bypass via API manipulation, and push fatigue.",
    folderPath: "skills/enterprise/okta-attack",
  },
  {
    id: "enterprise/hunt-sharepoint",
    name: "SharePoint Hunter",
    command: "/hunt-sharepoint",
    domain: "enterprise",
    env: "both",
    description: "SharePoint and OneDrive attack surface — anonymous file access, OOTB webpart XSS, SPFx extension injection, and internal metadata leak.",
    folderPath: "skills/enterprise/hunt-sharepoint",
  },
  {
    id: "enterprise/enterprise-vpn-attack",
    name: "Enterprise VPN Attack",
    command: "/enterprise-vpn-attack",
    domain: "enterprise",
    env: "both",
    description: "Enterprise VPN attack surface — Pulse Secure, Fortinet, Cisco AnyConnect pre-auth RCE, credential spray, and split-tunnel leak patterns.",
    folderPath: "skills/enterprise/enterprise-vpn-attack",
  },
  {
    id: "enterprise/vmware-vcenter-attack",
    name: "VMware vCenter Attack",
    command: "/vmware-vcenter-attack",
    domain: "enterprise",
    env: "both",
    description: "VMware vCenter attack chain — CVE-2021-21985, CVE-2021-22005 pre-auth RCE, credential extraction from vCenter DB, and ESXi lateral movement.",
    folderPath: "skills/enterprise/vmware-vcenter-attack",
  },

  // red-team (4)
  {
    id: "red-team/apk-redteam-pipeline",
    name: "APK Red-Team Pipeline",
    command: "/apk-redteam-pipeline",
    domain: "red-team",
    env: "code",
    description: "End-to-end Android APK red-team — automated acquisition, jadx decompilation, secret grep, cert pinning bypass, Frida instrumentation templates.",
    reportCount: 1,
    folderPath: "skills/red-team/apk-redteam-pipeline",
  },
  {
    id: "red-team/supply-chain-attack-recon",
    name: "Supply Chain Recon",
    command: "/supply-chain-attack-recon",
    domain: "red-team",
    env: "both",
    description: "Supply chain attack reconnaissance — dependency confusion targets, npm/PyPI namespace squatting, CI/CD pipeline poisoning vectors.",
    folderPath: "skills/red-team/supply-chain-attack-recon",
  },
  {
    id: "red-team/mid-engagement-ir-detection",
    name: "IR Detection Awareness",
    command: "/mid-engagement-ir-detection",
    domain: "red-team",
    env: "both",
    description: "Mid-engagement IR detection signals — EDR telemetry patterns, SIEM correlation rules that trigger on common techniques, detection-aware pivoting.",
    folderPath: "skills/red-team/mid-engagement-ir-detection",
  },
  {
    id: "red-team/redteam-mindset",
    name: "Red Team Mindset",
    command: "/redteam-mindset",
    domain: "red-team",
    env: "both",
    description: "Red team cognitive framework — objective-first thinking, OPSEC discipline, persistence prioritization, and engagement debrief methodology.",
    folderPath: "skills/red-team/redteam-mindset",
  },

  // recon-osint (3)
  {
    id: "recon/osint-methodology",
    name: "OSINT Methodology",
    command: "/osint-methodology",
    domain: "recon",
    env: "both",
    description: "5-stage recon pipeline with 29 asset types, identity-fabric mapping (Entra/Okta/ADFS), crypto tracing, image geolocation, and attribution workflows.",
    folderPath: "skills/recon-osint/osint-methodology",
  },
  {
    id: "recon/offensive-osint",
    name: "Offensive OSINT",
    command: "/offensive-osint",
    domain: "recon",
    env: "both",
    description: "Offensive OSINT techniques for authorized red-team engagements — breach correlation, LinkedIn harvesting, infrastructure pivot trails.",
    folderPath: "skills/recon-osint/offensive-osint",
  },
  {
    id: "recon/hunt-subdomain",
    name: "Subdomain Hunter",
    command: "/hunt-subdomain",
    domain: "recon",
    env: "code",
    description: "Subdomain enumeration and takeover identification — passive/active discovery, dangling DNS patterns, and scope expansion strategy.",
    folderPath: "skills/recon-osint/hunt-subdomain",
  },

  // reporting (5)
  {
    id: "reporting/triage-validation",
    name: "Triage Validation",
    command: "/triage-validation",
    domain: "reporting",
    env: "both",
    description: "7-Question Gate pre-submission workflow — 4 pre-submission gates, always-rejected list, CVSS 3.1 quick reference, and 60-second pre-submit checklist.",
    folderPath: "skills/reporting/triage-validation",
  },
  {
    id: "reporting/report-writing",
    name: "Report Writing",
    command: "/report-writing",
    domain: "reporting",
    env: "both",
    description: "Bug bounty report writing for H1/Bugcrowd/Intigriti/Immunefi — impact-first templates, CVSS 3.1 scoring, title formula, and downgrade counters.",
    folderPath: "skills/reporting/report-writing",
  },
  {
    id: "reporting/evidence-hygiene",
    name: "Evidence Hygiene",
    command: "/evidence-hygiene",
    domain: "reporting",
    env: "both",
    description: "Evidence collection and hygiene — screenshot standards, video PoC requirements, request/response sanitization, and metadata scrubbing.",
    folderPath: "skills/reporting/evidence-hygiene",
  },
  {
    id: "reporting/bugcrowd-reporting",
    name: "Bugcrowd Reporting",
    command: "/bugcrowd-reporting",
    domain: "reporting",
    env: "both",
    description: "Bugcrowd-specific report templates, VRT alignment, P1–P5 severity mapping, and platform-specific submission best practices.",
    folderPath: "skills/reporting/bugcrowd-reporting",
  },
  {
    id: "reporting/redteam-report-template",
    name: "Red Team Report",
    command: "/redteam-report-template",
    domain: "reporting",
    env: "both",
    description: "Executive and technical red team report template — attack narrative, kill chain visualization, risk rating matrix, and remediation roadmap.",
    folderPath: "skills/reporting/redteam-report-template",
  },

  // specialized (2)
  {
    id: "specialized/web3-audit",
    name: "Web3 Smart Contract Audit",
    command: "/web3-audit",
    domain: "specialized",
    env: "both",
    description: "Smart contract security audit — 10 DeFi bug classes, Foundry PoC template, grep patterns per class, and real Immunefi paid examples.",
    folderPath: "skills/specialized/web3-audit",
  },
  {
    id: "specialized/meme-coin-audit",
    name: "Meme Coin Audit",
    command: "/meme-coin-audit",
    domain: "specialized",
    env: "both",
    description: "Meme coin and low-TVL token audit — rug-pull pattern detection, honeypot identification, ownership renounce verification, and liquidity lock analysis.",
    folderPath: "skills/specialized/meme-coin-audit",
  },
];

export function getSkill(id: string): Skill | undefined {
  return skills.find((s) => s.id === id);
}

export function getSkillsByDomain(domain: string): Skill[] {
  return skills.filter((s) => s.domain === domain);
}
